### ISSUE TITLE
With the latest version of ImageTweak (0.22) and FF 4.0.1, can't close first tab!

### ISSUE THREAD

**Issue by PanzerIV88** [CAFxX/ImageTweak#10]
It's very annoying not to be able to close the first tab and it makes FF crash when closing the last closable tab, first one being "frozen". I'm not the only one to have this bug if you look at the reviews on the addon website.

**Comment by CAFxX** [comment]
This is not a bug of ImageTweak. See here for instructions on how to find out if a problem is caused by a bug in ImageTweak or by something else: https://github.com/CAFxX/ImageTweak/wiki/Troubleshooting

Besides, if you go on the addon website, you'll see that the first review now reads:

No bug in the latest version (0.22)

Finally, after disabling all add-ons, I have reactivated all, one by one (or more precisely two by two) starting with ImageTweak and the bug has mysteriously disappeared! --- (I remind you what was the original problem: "since the last update (version 0.22), it is impossible to close the first tab") --- Now, there is no problem.

Rated 5 out of 5 stars by creib on May 26, 2011
