### ISSUE TITLE
Problem with 'Notify websites' option

### ISSUE THREAD

**Issue by streetwolf** [CAFxX/ImageTweak#20]
WIth Notify Websites enabled I can't post a reply in this forum:  http://rootzwiki.com/topic/8424-rom-ics-thunderbolt-alpha35/

**Comment by CAFxX** [comment]
Does the error console report any error when trying to post with notify websites enabled?

**Comment by streetwolf** [comment]
Carlo:

I should have mentioned that I am running the nightly of Firefox/11.0a1.

I attached two screen shots of what is happening.  The first one (Capture) 
is how the reply field looks before anything is entered into it.  The second 
(Capture1) is when I click within the reply edit field.  With 'Notify 
websites' enabled I don't get the second screen, it just remains as is and 
of course I can't enter anything.

The error console looks like this with Nw enabled:

Error: uncaught exception: [Exception... "Component returned failure code: 
0x8000ffff (NS_ERROR_UNEXPECTED) [nsIDOMHTMLDocument.open]"  nsresult: 
"0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: 
http://rootzwiki.com/public/js/3rd_party/ckeditor/ckeditor.js :: <TOP_LEVEL> 
:: line 13"  data: no]

I don't get this message when Nw is disabled.  Hopes this helps.

-----Original Message-----

**Comment by CAFxX** [comment]
Does this happen also on a clean profile with just ImageTweak installed? Does this happen on Firefox 10 w/ clean profile as well? I must ask, because the only thing that option does is having a function called on each page (https://github.com/CAFxX/ImageTweak/blob/master/content/imagetweak.js#L621) that only inserts a single property (imageViewer) in the window.navigator object. That's it, nothing more. As such, I can't really imagine why a form would stop working because a non-standardized DOM object (window.navigator) has an additional member (imageViewer).

**Comment by streetwolf** [comment]
Carlo:
1.  No problem using latest Fx/8
2.  No problem using Fx10 nightly Aurora build.
3.  Does not work with Fx/11 using a clean profile and only Image Tweak.

I don’t know if this has anything to due with my problem but the default 
editor was changed to the Orion Editor or perhaps a newer version of it. I 
think this was done with Fx/11  One of the major addons that didn't work 
correctly because of this was Stylish.  I think Jason B. is now using his 
own editor in Stylish until a fix is issued.

-----Original Message-----

**Comment by CAFxX** [comment]
Is this issue still happening?

**Comment by streetwolf** [comment]
I should have updated this earlier.  This is no longer an issue.  All works fine now.

**Comment by CAFxX** [comment]
Ok, then I'm closing this. Thanks.
