### ISSUE TITLE
Streatch to window

### ISSUE THREAD

**Issue by IdeaHat** [CAFxX/ImageTweak#4]
Hey guys. I love this add on, but was wondering if you could add a "Stretch small images" feature. I use an HDTV as my monitor, so small images end up taking up a small portion of the screen. While centering images and putting them on a background helped the visual appearance, it would be great is small images were blown up to fill the screen.

**Comment by CAFxX** [comment]
I will do it sooner or later - patches welcome.

**Comment by CAFxX** [comment]
BTW, you can do it manually by clicking the "1" key or by left-clicking on the image and selecting "Fit image to screen"

**Comment by IdeaHat** [comment]
I'd be willing to try and mess around with the code to get this in, but to
be honest I've never written add dons before, and only have done Java script
for ImageJ., so this is going to be a learning experience. I programm for
work, but typically at a low-level (c, c++). Do you know of any good
resources/tutorials online to get started?

Thanks,

**Comment by CAFxX** [comment]
It won't be hard because the syntax of JS is very similar to C and all you need to do is poke around in imagetweak.js to make it do what you want (hint: the logic you need to change is here: https://github.com/CAFxX/ImageTweak/blob/master/content/imagetweak.js#L502) and then exposing the behaviour in a preference (look from line 747 onwards and in the preferences/imagetweak.js file) and eventually in the GUI (content/prefs.xul)
