### ISSUE TITLE
Incompatible with Grab&Drag

### ISSUE THREAD

**Issue by Efimero** [CAFxX/ImageTweak#5]
If Grab and Drag is enabled, dragging the image won't work. Clicking the Grab and Drag button to disable it works fine, but it would be much better if the issue was fixed, either by disabling Grab and Drag when ImageTweak is working or working an alternate way.
Thank you.

**Comment by CAFxX** [comment]
I can't unilaterally disable an extension. Such problems have already been fixed in the past (https://github.com/CAFxX/ImageTweak/issues/1) but the other extension needs to expose some API (a preference typically) that I can set to disable it at least when the document is a nsMediaDocument.
Please point this discussion to the developer of the other extension so that we can sort everything out.

**Comment by Efimero** [comment]
I sent an email to the author of Gran&Drag, since it's the only means of communication on his web. Hope you both can find a solution soon. Thanks.

**Comment by Efimero** [comment]
It seems Grab&Drag already had a solution for this. Here is the response from the author:

---

Any extension can turn Grab and Drag on and off in Javascript by setting the boolean preference "grabAndDrag.on" to true or false. However for ImageTweak there is a better solution since you want it to be disabled only for the tab containing the image. To do this ImageTweak just needs to set the document's BODY element to have the property "disableGrabAndDrag" set to "true". G&D automatically disables on page with this property in it's body element. This should be a simple one-line addition to the code. Future versions of Grab and Drag will probably have a whitelist/blacklist feature as well..

---

**Comment by CAFxX** [comment]
I applyied the suggested fix. I'll close the issue for now, let me know if there are still problems.
